import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navbar from "../components/shared/Navbar";
import '@fortawesome/fontawesome-svg-core/styles'
import Footer from "../components/shared/Footer";

import {Exo} from 'next/font/google'

const exo = Exo({
  subsets:['latin'],
  weight:['400', '500','600','700'],
  variable:'--font-exo'
})




export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased ${exo.className} font-medium`}
      >
         <Navbar />
        <div className=" bg-gray-50">
          <div className="max-w- mx-auto">
            {children}
          </div>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
